---
mirror_packages:
  - nginx

nginx_user: www-data
nginx_group: www-data

#mirror_root: /usr/share/nginx/html
mirror_root: /var/www/html
repositories:
  - name: ansible_base
    description: CentOS-7 - Base
    protocol: https
    url: "mirror.liquidtelecom.com/centos/7/os/x86_64/"
    directory: centos/7/os/x86_64
  - name: ansible_updates
    description: CentOS-7 - Updates
    protocol: https
    url: "mirror.liquidtelecom.com/centos/7/updates/x86_64/"
    directory: centos/7/updates/x86_64
  - name: ansible_extras
    description: CentOS-7 - Extras
    protocol: https
    url: "mirror.liquidtelecom.com/centos/7/extras/x86_64/"
    directory: centos/7/extras/x86_64
  - name: ansible_centosplus
    description: CentOS-7 - Plus
    protocol: https
    url: "mirror.liquidtelecom.com/centos/7/centosplus/x86_64/"
    directory: centos/7/centosplus/x86_64
  - name: ansible_epel
    description: Extra Packages for Enterprise Linux 7 - x86_64
    protocol: http
    url: "mirrors.liquidweb.com/fedora-epel/7/x86_64/"
    directory: epel/7/x86_64
keys:
  - url: "mirror.liquidtelecom.com/centos/RPM-GPG-KEY-CentOS-7"
    directory: centos
  - url: "mirrors.liquidweb.com/fedora-epel/RPM-GPG-KEY-EPEL-7"
    directory: epel