---
- name: Find default repo configs
  find:
    paths: 
      - /etc/yum.repos.d/
    patterns: "{{ legacy_repo_files }}"
  register: files_to_delete

- name: Remove default repo configs
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: "Add YUM repos"
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.protocol }}://{{ item.url }}"
    description: "{{ item.description }}"
    enabled: yes
    ip_resolve: IPv4
  with_items: "{{ mirrors }}"
  loop_control:
    label: "{{ item.description }}"