- name: Setup PiHole
  hosts: dns
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Combine composes
      set_fact:
        composes: "{{ composes|default({}) | combine(hostvars[inventory_hostname]['compose_' + item]|default({})) }}"
      loop: "{{ group_names }}"
  roles:
    - ../../../../roles/yum-repos
    - ../../../../roles/firewall
    - ../../../../roles/docker
    - chrisbalmer.docker-compose
    - ../../../../roles/pihole
