---
- name: Build repository details with port
  set_fact:
    registry_url: "{{ registry_protocol }}://{{ registry_server }}:{{ registry_port }}"
    repository_name: "{{ registry_server }}:{{ registry_port }}"
  when: registry_port is defined

- name: Build repository details without port
  set_fact:
    registry_url: "{{ registry_protocol }}://{{ registry_server }}"
    repository_name: "{{ registry_server }}"
  when: registry_port is not defined

- name: Install required packages for mirroring
  package:
    name: "{{ mirror_packages }}"
    state: latest

- name: Log into private registry
  community.general.docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"

- name: Pull needed images
  community.general.docker_image:
    name: "{{ item.name }}:{{ item.tag }}"
    source: pull
  with_items: "{{ docker_images }}"
  loop_control:
    label: "{{ item.name }}:{{ item.tag }}"

- name: Tag and push images to local registry
  community.general.docker_image:
    name: "{{ item.name }}"
    repository: "{{ repository_name }}/{{ item.name }}"
    tag: "{{ item.tag }}"
    push: yes
    source: local
  with_items: "{{ docker_images }}"
  loop_control:
    label: "{{ item.name }}:{{ item.tag }}"
