- name: Install AWX Server
  hosts: awx
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Combine composes
      set_fact:
        composes: "{{ composes|default({}) | combine(hostvars[inventory_hostname]['compose_' + item]|default({})) }}"
      loop: "{{ group_names }}"
  roles:
    - ../../../../roles/firewall
    - ../../../../roles/yum-repos
    - chrisbalmer.nfs
    - ../../../../roles/docker
    - chrisbalmer.docker-compose
    - ../../../../../ansible-role-awx/
  tasks:

    - name: Wait for traefik to create required certs
      pause:
        minutes: 1

    - name: Setup Tower CLI
      template:
        src: tower_cli.cfg.j2
        dest: ~/.tower_cli.cfg

    - name: Create tower organization
      awx.awx.tower_organization:
        name: "{{ item.name }}"
        state: present
      loop: "{{ awx_organizations }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Add 1Password Credential Type
      awx.awx.tower_credential_type:
        name: 1Password Login
        kind: net
        inputs:
          fields:
            - id: op_email
              type: string
              label: 1Password Email
            - id: op_domain
              type: string
              label: 1Password Domain (i.e. my for non-business)
            - id: op_key
              type: string
              label: 1Password Key
              secret: true
            - id: op_password
              type: string
              label: 1Password Password
              secret: true
          required:
            - op_email
            - op_domain
            - op_key
            - op_password
        injectors:
          extra_vars:
            op_domain: "{{ '{{' }} op_domain {{ '}}' }}"
            op_email: "{{ '{{' }} op_email {{ '}}' }}"
            op_key: "{{ '{{' }} op_key {{ '}}' }}"
            op_password: "{{ '{{' }} op_password {{ '}}' }}"

    - name: Add credentials
      awx.awx.tower_credential:
        credential_type: "{{ item.1.type }}"
        name: "{{ item.1.name }}"
        inputs: "{{ item.1.inputs }}"
        organization: "{{ item.0.name }}"
      loop: "{{ q('subelements', awx_organizations, 'credentials', {'skip_missing': True}) }}"
      loop_control:
        label: "{{ item.0.name }} - {{ item.1.name }}"

    - name: Add inventories
      awx.awx.tower_inventory:
        name: "{{ item.1.name }}"
        description: "{{ item.1.description }}"
        organization: "{{ item.0.name }}"
        state: present
        variables: "{{ item.1.variables | default({}) }}"
      loop: "{{ q('subelements', awx_organizations, 'inventories', {'skip_missing': True}) }}"
      loop_control:
        label: "{{ item.0.name }} - {{ item.1.name }}"

    - name: Combine all inventories
      set_fact:
        awx_all_inventories: >
          {{ awx_all_inventories|d([])
            + [ {} | combine({'org': item.0.name}) | combine(item.1) ]
          }}
      loop: "{{ q('subelements', awx_organizations, 'inventories', {'skip_missing': True}) }}"
      loop_control:
        label: "{{ item.0.name }} - {{ item.1.name }}"

    - name: Add inventory sources
      awx.awx.tower_inventory_source:
        name: "{{ item.1.name }}"
        description: "{{ item.1.description }}"
        inventory: "{{ item.0.name }}"
        credential: "{{ item.1.credential }}"
        overwrite: "{{ item.1.overwrite }}"
        update_on_launch: "{{ item.1.update_on_launch }}"
        organization: "{{ item.0.org }}"
        source: "{{ item.1.source }}"
        source_vars: "{{ item.1.vars }}"
      loop: "{{ q('subelements', awx_all_inventories, 'sources', {'skip_missing': True}) }}"
      loop_control:
        label: "{{ item.0.org }} - {{ item.0.name }} - {{ item.1.name }}"
      


    - name: Add hosts
      awx.awx.tower_host:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        inventory: "{{ item.inventory }}"
        state: present
      loop: "{{ awx_hosts }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Add projects
      awx.awx.tower_project:
        name: "{{ item.1.name }}"
        description: "{{ item.1.description }}"
        organization: "{{ item.0.name }}"
        scm_type: git
        scm_branch: "{{ item.1.branch }}"
        scm_update_on_launch: False
        scm_url: "{{ item.1.git }}"
      loop: "{{ q('subelements', awx_organizations, 'projects', {'skip_missing': True}) }}"
      loop_control:
        label: "{{ item.0.name }} - {{ item.1.name }}"

    - name: Add templates
      awx.awx.tower_job_template:
        name: "{{ item.1.name }}"
        job_type: "{{ item.1.job_type }}"
        organization: "{{ item.0.name }}"
        inventory: "{{ item.1.inventory }}"
        project: "{{ item.1.project }}"
        playbook: "{{ item.1.playbook }}"
        state: "present"
      loop: "{{ q('subelements', awx_organizations, 'templates', {'skip_missing': True}) }}"
      loop_control:
        label: "{{ item.0.name }} - {{ item.1.name }}"

    - name: Add schedules
      awx.awx.tower_schedule:
        name: "{{ item.name }}"
        state: present
        unified_job_template: "{{ item.job_template }}"
        rrule: "{{ item.rrule }}"
      loop: "{{ awx_schedules }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Build organization mappings
      set_fact:
        awx_org_map: "{{ awx_org_map|default({}) | combine({item.name: item.map}) }}"
      loop: "{{ awx_organizations }}"
      when: item.map is not undefined
      loop_control:
        label: "{{ item.name }}"

    - name: Configure LDAP
      awx.awx.tower_settings:
        settings:
          AUTH_LDAP_SERVER_URI: "{{ awx_ldap_uri }}"
          AUTH_LDAP_BIND_DN: "{{ awx_ldap_bind_dn }}"
          AUTH_LDAP_BIND_PASSWORD: "{{ awx_ldap_bind_password }}"
          AUTH_LDAP_REQUIRE_GROUP: "{{ awx_ldap_require_group }}"
          AUTH_LDAP_GROUP_TYPE: "{{ awx_ldap_group_type }}"
          AUTH_LDAP_GROUP_SEARCH: "{{ awx_ldap_group_search }}"
          AUTH_LDAP_USER_SEARCH: "{{ awx_ldap_user_search }}"
          AUTH_LDAP_USER_ATTR_MAP: "{{ awx_ldap_attribute_map }}"
          AUTH_LDAP_USER_FLAGS_BY_GROUP: "{{ awx_ldap_user_flags_by_group }}"
          AUTH_LDAP_ORGANIZATION_MAP: "{{ awx_org_map }}"
