---
collections:
  - ansible.posix
  - community.general
  - awx.awx

roles:
  - name: chrisbalmer.docker-compose
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-docker-compose.git
    version: v1.2.0
  - name: chrisbalmer.nfs
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-nfs.git
    version: 2.1.1
    