---
collections:
  - ansible.posix
  - community.general
  - name: awx.awx
    version: 17.0.1

roles:
  - name: chrisbalmer.docker-compose
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-docker-compose.git
    version: v1.2.0
  - name: chrisbalmer.nfs
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-nfs.git
    version: 2.1.1
  - name: chrisbalmer.yum-repos
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-yum-repos.git
    version: v0.0.1
  - name: chrisbalmer.firewall
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-firewall.git
    version: v0.0.1
  - name: chrisbalmer.simple-docker
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-simple-docker.git
    version: v0.0.1
  - name: chrisbalmer.awx
    scm: git
    src: git+https://github.com/chrisbalmer/ansible-role-awx.git
    version: 17.0.1-0001
