---
config_path: /etc/ansible-role-docker-compose
traefik_network: traefik
docker_timeout: 7200
docker_package_timeout: "{{ docker_timeout }}"
docker_registry: docker-registry.balmerfamilyfarm.com
nfs_server: 172.21.129.36
# splunk:
#   hec_token: "{{ lookup('onepassword', 'Docker Servers', section='splunk', field='token', vault='homelab') }}"
#   hec_endpoint: "http://opscriblmgr1.farm.oakops.io:8088"
#   hec_format: json
#   hec_skip_verify: true
