---
- name: Open firewall services
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ firewall_services | default([]) }}"

- name: Open firewall ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ firewall_ports | default([]) }}"
