---
dockerhub_base: "{{ docker_registry }}/ansible"
awx_task_hostname: awx
awx_web_hostname: awxweb
postgres_data_dir: "~/.awx/pgdocker"
host_port: 80
host_port_ssl: 443
docker_compose_dir: "~/.awx/awxcompose"

pg_username: "{{ lookup('onepassword', 'AWX Balmer Family Farm DBMS - admin', field='username', vault='homelab') }}"
pg_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm DBMS - admin', field='password', vault='homelab') }}"
pg_database: awx
pg_port: 5432

admin_user: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='username', vault='homelab') }}"
admin_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='password', vault='homelab') }}"
secret_key: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='key', vault='homelab') }}"
project_data_dir: /var/lib/awx/projects

awx_domain: awx.balmerfamilyfarm.com

awx_web_container_labels:
  - "traefik.enable=true"
  - "traefik.http.routers.awx.rule=Host(`{{ awx_domain }}`)"
  - "traefik.http.routers.awx.tls=true"
  - "traefik.http.routers.awx.tls.certresolver=letsencrypt"
  - "traefik.http.services.awx.loadbalancer.server.port=8052"
  - "traefik.docker.network={{ traefik_network }}"

awx_organization: Balmer Family Farm

awx_projects:
  - name: 1Password AWX Setup
    description: Install the 1Password Binary on the AWX Container
    git: https://github.com/chrisbalmer/ansible-playbook-onepassword-setup.git
    branch: v1.0.1


awx_ldap_uri: "ldap://opsad1.ad.balmerfamilyfarm.com:389"
awx_ldap_bind_dn: "{{ lookup('onepassword', 'AWX Balmer Family Farm - ldap', field='username', vault='homelab') }}"
awx_ldap_bind_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm - ldap', field='password', vault='homelab') }}"
awx_ldap_require_group: "CN=AWX Users,CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
awx_ldap_group_type: "GroupOfNamesType"
awx_ldap_group_search:
  - "CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
  - "SCOPE_SUBTREE"
  - "(objectClass=groupOfNames)"
awx_ldap_user_search:
  - "CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
  - "SCOPE_SUBTREE"
  - "(sAMAccountName=%(user)s)"
awx_ldap_attribute_map:
  first_name: "givenName"
  last_name: "sn"
  email: "mail"
awx_ldap_user_flags_by_group:
  is_superuser: "CN=AWX Admins,CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
awx_ldap_org_map:
  "Balmer Family Farm":
    admins: "CN=AWX Admins,CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
    remove_users: false
    remove_admins: false
    users: true