---
# General settings
dockerhub_version: 17.1.0
dockerhub_base: "{{ docker_registry }}/chrisbalmer"
awx_task_hostname: awx
awx_web_hostname: awxweb
postgres_data_dir: "~/.awx/pgdocker"
host_port: 80
host_port_ssl: 443
docker_compose_dir: "~/.awx/awxcompose"

# DBMS settings
pg_username: "{{ lookup('onepassword', 'AWX Balmer Family Farm DBMS - admin', field='username', vault='homelab') }}"
pg_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm DBMS - admin', field='password', vault='homelab') }}"
pg_database: awx
pg_port: 5432

# AWX local admin settings
admin_user: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='username', vault='homelab') }}"
admin_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='password', vault='homelab') }}"
secret_key: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='key', vault='homelab') }}"


# Container settings
project_data_dir: /var/lib/awx/projects
awx_domain: awx.balmerfamilyfarm.com
awx_web_container_labels:
  - "traefik.enable=true"
  - "traefik.http.routers.awx.rule=Host(`{{ awx_domain }}`)"
  - "traefik.http.routers.awx.tls=true"
  - "traefik.http.routers.awx.tls.certresolver=letsencrypt"
  - "traefik.http.services.awx.loadbalancer.server.port=8052"
  - "traefik.docker.network={{ traefik_network }}"
docker_compose_extra_hosts:
  - "nas.balmerfamilyfarm.com:172.21.129.36"
# Organization specific configs
awx_organizations:
  - name: Balmer Family Farm
    map:
      admins: "CN=AWX Admins,CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
      remove_users: false
      remove_admins: false
      users: true
    galaxy_credential: Galaxy Default Credential
    credentials:
      - name: vcenter.balmerfamilyfarm.com
        type: VMware vCenter
        inputs:
          host: "vcenter.balmerfamilyfarm.com"
          username: "svc_awx@ad.balmerfamilyfarm.com"
          password: "{{ lookup('onepassword', 'AWX Balmer Family Farm - ldap', field='password', vault='homelab') }}"
      - name: 1Password
        type: 1Password Login 
        inputs:
          op_email: "{{ lookup('onepassword', '1Password - Automation', field='username', vault='homelab') }}"
          op_domain: "my"
          op_key: "{{ lookup('onepassword', '1Password Account - automation', field='secret key', vault='homelab') }}"
          op_password: "{{ lookup('onepassword', '1Password - Automation', field='password', vault='homelab') }}"
      - name: Galaxy Default Credential
        type: Ansible Galaxy/Automation Hub API Token
        inputs:
          url: https://galaxy.ansible.com
    inventories:
      - name: "Local Inventory"
        description: "AWX Container"
        variables:
          ansible_connection: local
          op_version: 1.8.0
          python3_libraries:
            - name: git+https://github.com/vmware/vsphere-automation-sdk-python.git
      - name: "vCenter"
        description: "VMs from vCenter"
        sources:
          - name: vCenter Plugin
            description: Pulls inventory from vCenter
            credential: vcenter.balmerfamilyfarm.com
            overwrite: True
            update_on_launch: True
            source: vmware
            vars:
              with_tags: True
              keyed_groups:
                - key: tag_category.ansible_groups
                  prefix: "vmware_tag_ansible_groups_"
                  separator: ""
              filters:
                - config.template == false
                - summary.runtime.powerState == "poweredOn"
      - name: "Bootstrap"
        description: "Systems used to bootstrap the homelab"
    projects:
      - name: AWX Configuration
        description: For configuring AWX
        git: https://github.com/chrisbalmer/ansible-playbooks-awx.git
        branch: v1.0.0
      - name: homelab-linux
        description: Standard Linux Configuration
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-linux.git
        branch: v0.0.1
      - name: homelab-docker
        description: For setting up docker hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-docker.git
        branch: netbox_build
        update_on_launch: True
      - name: homelab-splunk
        description: For setting up Splunk hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-splunk.git
        branch: master
        update_on_launch: True
      - name: homelab-dns
        description: For setting up DNS hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-dns.git
        branch: v0.2.0
      - name: homelab-dhcp
        description: For setting up DHCP hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-dhcp.git
        branch: v0.0.2
      - name: homelab-sso
        description: For setting up SSO hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-sso.git
        branch: master
    templates:
      - name: 1Password on AWX
        job_type: run
        inventory: Local Inventory
        project: AWX Configuration
        playbook: 1password.yml
      - name: Install Python3 Libraries on AWX
        job_type: run
        inventory: Local Inventory
        project: AWX Configuration
        playbook: python3-libraries.yml
      - name: Configure Docker Hosts
        job_type: run
        inventory: vCenter
        project: homelab-docker
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Test
      - name: Standard Linux Configuration
        job_type: run
        inventory: vCenter
        project: homelab-linux
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - Test
      - name: Install/Upgrade Splunk
        job_type: run
        inventory: vCenter
        project: homelab-splunk
        playbook: install_splunk.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Test
      - name: Configure DNS Servers
        job_type: run
        inventory: vCenter
        project: homelab-dns
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Test
      - name: Configure DHCP Servers
        job_type: run
        inventory: vCenter
        project: homelab-dhcp
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - Test
      - name: Configure SSO Servers
        job_type: run
        inventory: vCenter
        project: homelab-sso
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Test
  - name: Org2

# Non organization specific configs
awx_schedules:
  - name: Keep 1Password on AWX Container
    job_template: 1Password on AWX
    rrule: "DTSTART:20191219T130551Z RRULE:FREQ=MINUTELY;INTERVAL=30"
awx_hosts:
  - name: localhost
    description: "AWX Container"
    inventory: "Local Inventory"
awx_vmware_groups:
  - name: vmware_tag_ansible_groups_dhcp
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_docker
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_jira
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_confluence
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_linux
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_windows
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_wikijs
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_gitea
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_netbox
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_traefik
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_full
    description: "Splunk Full Install"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_uf
    description: "Splunk Universal Forwarder"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_clustermaster
    description: "Splunk Cluster Master"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_deploymentserver
    description: "Splunk Deployment Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_indexer
    description: "Splunk Indexer"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_licensemaster
    description: "Splunk License Master"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_search
    description: "Splunk Search Head"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_shdeployer
    description: "Splunk Search Head Deployer"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_pihole
    description: "PiHole Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_dns
    description: "DNS Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_sso
    description: "SSO Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_xsoar
    description: "XSOAR Server"
    inventory: vCenter

awx_groups:
  - name: dhcp
    description: "DHCP servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_dhcp
    variables:
      firewall_services:
        - dhcp
      firewall_ports:
        - 647/tcp
        - 847/tcp

  - name: linux
    description: "Linux servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_linux

  - name: windows
    description: "Windows systems"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_windows
    variables:
      ansible_connection: winrm

  - name: docker_hosts
    description: "Docker hosts"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_docker
    variables:
      firewall_services:
        - http
        - https

  - name: jira
    description: "Jira servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_jira

  - name: confluence
    description: "Confluence servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_confluence

  - name: wikijs
    description: "WikiJS servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_wikijs

  - name: gitea
    description: "Gitea servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_gitea

  - name: netbox
    description: "Netbox servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_netbox

  - name: traefik
    description: "Traefik servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_traefik

  - name: full
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_full

  - name: uf
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_uf

  - name: clustermaster
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_clustermaster
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp

  - name: deploymentserver
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_deploymentserver
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp    

  - name: indexer
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_indexer
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp
        - 9997/tcp
        - 9887/tcp

  - name: licensemaster
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_licensemaster
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp

  - name: search
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_search
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp
        - 9777/tcp
        - 8191/tcp

  - name: shdeployer
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_shdeployer
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp

  - name: pihole
    description: "PiHole Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_pihole
    variables:
      firewall_services:
        - dns
        - http
        - https

  - name: dns
    description: "DNS Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_dns
  
  - name: sso
    description: "SSO Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_sso
    variables:
      firewall_services:
        - http
        - https

  - name: xsoar
    description: "XSOAR Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_xsoar
    variables:
      firewall_services:
        - http
        - https

# Global LDAP Settings
awx_ldap_uri: "ldap://opsad1.ad.balmerfamilyfarm.com:389"
awx_ldap_bind_dn: "{{ lookup('onepassword', 'AWX Balmer Family Farm - ldap', field='username', vault='homelab') }}"
awx_ldap_bind_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm - ldap', field='password', vault='homelab') }}"
awx_ldap_require_group: "CN=AWX Users,CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
awx_ldap_group_type: "GroupOfNamesType"
awx_ldap_group_search:
  - "CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
  - "SCOPE_SUBTREE"
  - "(objectClass=groupOfNames)"
awx_ldap_user_search:
  - "CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
  - "SCOPE_SUBTREE"
  - "(sAMAccountName=%(user)s)"
awx_ldap_attribute_map:
  first_name: "givenName"
  last_name: "sn"
  email: "mail"
awx_ldap_user_flags_by_group:
  is_superuser: "CN=AWX Admins,CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"

# Device ID can be generated via https://1password.community/discussion/comment/563411/#Comment_563411
awx_task_env:
  HOME: /var/lib/awx
  OP_DEVICE: "{{ lookup('onepassword', '1Password - Automation', field='device_id', vault='homelab') }}"