---
# General settings
dockerhub_version: 17.1.0
dockerhub_base: "{{ docker_registry }}/chrisbalmer"
awx_task_hostname: awx
awx_web_hostname: awxweb
postgres_data_dir: "~/.awx/pgdocker"
host_port: 80
host_port_ssl: 443
docker_compose_dir: "~/.awx/awxcompose"

# DBMS settings
pg_username: "{{ lookup('onepassword', 'AWX Balmer Family Farm DBMS - admin', field='username', vault='homelab') }}"
pg_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm DBMS - admin', field='password', vault='homelab') }}"
pg_database: awx
pg_port: 5432

# AWX local admin settings
admin_user: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='username', vault='homelab') }}"
admin_password: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='password', vault='homelab') }}"
secret_key: "{{ lookup('onepassword', 'AWX Balmer Family Farm - admin', field='key', vault='homelab') }}"


# Container settings
project_data_dir: /var/lib/awx/projects
awx_domain: awx.balmerfamilyfarm.com
awx_web_container_labels:
  - "traefik.enable=true"
  - "traefik.http.routers.awx.rule=Host(`{{ awx_domain }}`)"
  - "traefik.http.routers.awx.tls=true"
  - "traefik.http.routers.awx.tls.certresolver=letsencrypt"
  - "traefik.http.services.awx.loadbalancer.server.port=8052"
  - "traefik.docker.network={{ traefik_network }}"
docker_compose_extra_hosts:
  - "nas.balmerfamilyfarm.com:172.21.129.36"
# Organization specific configs
awx_organizations:
  - name: Balmer Family Farm
    map:
      admins: "CN=AWX Admins,CN=Users,DC=ad,DC=balmerfamilyfarm,DC=com"
      remove_users: false
      remove_admins: false
      users: true
    galaxy_credential: Galaxy Default Credential
    teams:
      - name: "AWX-Farm-Engineers"
        description: "Main management for AWX"
        state: "present"
    credentials:
      - name: vcenter.balmerfamilyfarm.com
        type: VMware vCenter
        inputs:
          host: "vcenter.balmerfamilyfarm.com"
          username: "svc_awx@ad.balmerfamilyfarm.com"
          password: "{{ lookup('onepassword', 'AWX Balmer Family Farm - ldap', field='password', vault='homelab') }}"
      - name: 1Password
        type: 1Password Login 
        inputs:
          op_email: "{{ lookup('onepassword', '1Password - Automation', field='username', vault='homelab') }}"
          op_domain: "my"
          op_key: "{{ lookup('onepassword', '1Password Account - automation', field='secret key', vault='homelab') }}"
          op_password: "{{ lookup('onepassword', '1Password - Automation', field='password', vault='homelab') }}"
      - name: Galaxy Default Credential
        type: Ansible Galaxy/Automation Hub API Token
        inputs:
          url: https://galaxy.ansible.com
      - name: Linux SSH
        type: Machine
        inputs:
          username: "{{ lookup('onepassword', 'awx.balmerfamilyfarm.com ssh key', field='username', vault='homelab') }}"
          ssh_key_data: "-----BEGIN OPENSSH PRIVATE KEY-----\n{{ lookup('onepassword', 'awx.balmerfamilyfarm.com ssh key', field='ssh key', vault='homelab') }}\n-----END OPENSSH PRIVATE KEY-----"
          become_method: "sudo"
          ssh_key_unlock: "{{ lookup('onepassword', 'awx.balmerfamilyfarm.com ssh key', field='password', vault='homelab') }}"
          become_username: ""
    inventories:
      - name: "Local Inventory"
        description: "AWX Container"
        variables:
          ansible_connection: local
          op_version: 1.8.0
          python3_libraries:
            - name: git+https://github.com/vmware/vsphere-automation-sdk-python.git
      - name: "vCenter"
        description: "VMs from vCenter"
        sources:
          - name: vCenter Plugin
            description: Pulls inventory from vCenter
            credential: vcenter.balmerfamilyfarm.com
            overwrite: True
            update_on_launch: True
            source: vmware
            vars:
              with_tags: True
              keyed_groups:
                - key: tag_category.ansible_groups
                  prefix: "vmware_tag_ansible_groups_"
                  separator: ""
              filters:
                - config.template == false
                - summary.runtime.powerState == "poweredOn"
      - name: "Bootstrap"
        description: "Systems used to bootstrap the homelab"
    projects:
      - name: AWX Configuration
        description: For configuring AWX
        git: https://github.com/chrisbalmer/ansible-playbooks-awx.git
        branch: v1.0.0
      - name: homelab-linux
        description: Standard Linux Configuration
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-linux.git
        branch: v0.0.1
      - name: homelab-docker
        description: For setting up docker hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-docker.git
        branch: gitea_env
        update_on_launch: True
      - name: homelab-splunk
        description: For setting up Splunk hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-splunk.git
        branch: master
        update_on_launch: True
      - name: homelab-dns
        description: For setting up DNS hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-dns.git
        branch: v0.4.0
      - name: homelab-dhcp
        description: For setting up DHCP hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-dhcp.git
        branch: v0.0.2
      - name: homelab-sso
        description: For setting up SSO hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-sso.git
        branch: master
      - name: homelab-xsoar
        description: For setting up XSOAR hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-xsoar.git
        branch: master
      - name: homelab-cribl
        description: For setting up Cribl hosts
        git: https://github.com/chrisbalmer/ansible-playbook-homelab-cribl.git
        branch: alpha
    templates:
      - name: 1Password on AWX
        job_type: run
        inventory: Local Inventory
        project: AWX Configuration
        playbook: 1password.yml
      - name: Install Python3 Libraries on AWX
        job_type: run
        inventory: Local Inventory
        project: AWX Configuration
        playbook: python3-libraries.yml
      - name: Configure Docker Hosts
        job_type: run
        inventory: vCenter
        project: homelab-docker
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Linux SSH
      - name: Standard Linux Configuration
        job_type: run
        inventory: vCenter
        project: homelab-linux
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - Linux SSH
      - name: Install/Upgrade Splunk
        job_type: run
        inventory: vCenter
        project: homelab-splunk
        playbook: install_splunk.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Linux SSH
      - name: Configure DNS Servers
        job_type: run
        inventory: vCenter
        project: homelab-dns
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Linux SSH
      - name: Configure DHCP Servers
        job_type: run
        inventory: vCenter
        project: homelab-dhcp
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - Linux SSH
      - name: Configure SSO Servers
        job_type: run
        inventory: vCenter
        project: homelab-sso
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Linux SSH
      - name: Configure XSOAR Servers
        job_type: run
        inventory: vCenter
        project: homelab-xsoar
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Linux SSH
      - name: Configure Cribl Servers
        job_type: run
        inventory: vCenter
        project: homelab-cribl
        playbook: playbook.yml
        become: true
        store_facts: true
        credentials:
          - 1Password
          - Linux SSH
  - name: Org2

# Non organization specific configs
awx_schedules:
  - name: Keep 1Password on AWX Container
    job_template: 1Password on AWX
    rrule: "DTSTART:20191219T130551Z RRULE:FREQ=MINUTELY;INTERVAL=30"
awx_hosts:
  - name: localhost
    description: "AWX Container"
    inventory: "Local Inventory"
awx_vmware_groups:
  - name: vmware_tag_ansible_groups_dhcp
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_docker
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_jira
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_confluence
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_linux
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_windows
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_wikijs
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_gitea
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_netbox
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_traefik
    description: "VMware tagged group"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_full
    description: "Splunk Full Install"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_uf
    description: "Splunk Universal Forwarder"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_clustermaster
    description: "Splunk Cluster Master"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_deploymentserver
    description: "Splunk Deployment Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_indexer
    description: "Splunk Indexer"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_licensemaster
    description: "Splunk License Master"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_search
    description: "Splunk Search Head"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_shdeployer
    description: "Splunk Search Head Deployer"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_pihole
    description: "PiHole Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_dns
    description: "DNS Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_sso
    description: "SSO Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_xsoar
    description: "XSOAR Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_cribl
    description: "Cribl Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_cribl_manager
    description: "Cribl Manager Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_cribl_worker
    description: "Cribl Worker Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_zeek
    description: "Zeek Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_zeek_manager
    description: "Zeek Manager Server"
    inventory: vCenter
  - name: vmware_tag_ansible_groups_zeek_worker
    description: "Zeek Worker Server"
    inventory: vCenter

awx_groups:
  - name: dhcp
    description: "DHCP servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_dhcp
    variables:
      firewall_services:
        - dhcp
      firewall_ports:
        - 647/tcp
        - 847/tcp

  - name: linux
    description: "Linux servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_linux

  - name: windows
    description: "Windows systems"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_windows
    variables:
      ansible_connection: winrm

  - name: docker_hosts
    description: "Docker hosts"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_docker
    variables:
      firewall_services:
        - http
        - https

  - name: jira
    description: "Jira servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_jira

  - name: confluence
    description: "Confluence servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_confluence

  - name: wikijs
    description: "WikiJS servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_wikijs

  - name: gitea
    description: "Gitea servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_gitea

  - name: netbox
    description: "Netbox servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_netbox

  - name: traefik
    description: "Traefik servers"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_traefik

  - name: full
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_full

  - name: uf
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_uf

  - name: clustermaster
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_clustermaster
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp

  - name: deploymentserver
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_deploymentserver
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp    

  - name: indexer
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_indexer
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp
        - 9997/tcp
        - 9887/tcp

  - name: licensemaster
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_licensemaster
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp

  - name: search
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_search
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp
        - 9777/tcp
        - 8191/tcp

  - name: shdeployer
    description: "Splunk"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_shdeployer
    variables:
      firewall_ports:
        - 8000/tcp
        - 8089/tcp

  - name: pihole
    description: "PiHole Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_pihole
    variables:
      firewall_services:
        - dns
        - http
        - https

  - name: dns
    description: "DNS Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_dns
  
  - name: sso
    description: "SSO Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_sso
    variables:
      firewall_services:
        - http
        - https

  - name: xsoar
    description: "XSOAR Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_xsoar
    variables:
      firewall_services:
        - http
        - https

  - name: cribl
    description: "Cribl Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_cribl
    variables:
      firewall_services:
        - http
        - https

  - name: cribl_manager
    description: "Cribl Manager Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_cribl_manager
    variables:
      firewall_services:
        - http
        - https

  - name: cribl_worker
    description: "Cribl Worker Server"
    inventory: vCenter
    children:
      - vmware_tag_ansible_groups_cribl_worker
    variables:
      firewall_services:
        - http
        - https

awx_team_roles:
  - role: approval
    team: AWX-Farm-Engineers
    orgs:
      - Balmer Family Farm
  - role: execute
    team: AWX-Farm-Engineers
    orgs:
      - Balmer Family Farm
  - role: auditor
    team: AWX-Farm-Engineers
    orgs:
      - Balmer Family Farm



# Global SAML Settings
awx_saml_enabled: true
awx_saml_name: keycloak
awx_saml_redirect: "https://{{ awx_domain }}/sso/login/saml/?idp={{ awx_saml_name }}"
awx_saml_entity_id: awx
awx_saml_cert: "{{ lookup('onepassword', 'AWX Balmer Family Farm - certificate', field='public', vault='homelab') }}"
awx_saml_key: "{{ lookup('onepassword', 'AWX Balmer Family Farm - certificate', field='password', vault='homelab') }}"
awx_saml_org_info:
  en-US:
    url: "https://sso.balmerfamilyfarm.com"
    displayname: "Balmer Family Farm SSO"
    name: "{{ awx_saml_name }}"
awx_saml_contact:
  givenName: Chris Balmer
  emailAddress: chris@balmerfamilyfarm.com
awx_saml_idp:
  keycloak:
    attr_last_name: "urn:oid:2.5.4.4"
    attr_username: "urn:oid:1.2.840.113549.1.9.1"
    entity_id: "https://sso.balmerfamilyfarm.com/auth/realms/balmerfamilyfarm.com"
    attr_user_permanent_id: "urn:oid:1.2.840.113549.1.9.1"
    url: "https://sso.balmerfamilyfarm.com/auth/realms/balmerfamilyfarm.com/protocol/saml"
    attr_email: "urn:oid:1.2.840.113549.1.9.1"
    x509cert: "MIICtzCCAZ8CBgF4UBfukzANBgkqhkiG9w0BAQsFADAfMR0wGwYDVQQDDBRiYWxtZXJmYW1pbHlmYXJtLmNvbTAeFw0yMTAzMjAxNDQyMjhaFw0zMTAzMjAxNDQ0MDhaMB8xHTAbBgNVBAMMFGJhbG1lcmZhbWlseWZhcm0uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgBjx60gTpL+f/k20chPJ8bIDeq7N5d6OPoOQ7x7RGFqKyri7arjx329WGy1byHkw9ZsAPutC4zwk5BjNrPzIc8bfwLEr3QuQX38Njyeup1KY9mVUS5P3sB7NFlpEaFX756vDQ/LfuXkwd0ppvVRK5D4kiUcD3ppOABjoP6znw6vw1rYX+msSBEYSUqcVd1xIo+C9u1TQEYG2jgD1EGQghMovg1e6OpCAuFrNyovWgGOrb8NUHDM4aAiT3dfs9ajOaZEk0+qJ5Durzao7wlFXqSbT6Ur+/bj6XktNF/Xb3e3BovPzOjJeW5C+V9y5KKr/8iOpC25jP+zHh2Ucf4Qi+wIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAunQd+/yThqAcm/d7fFVakwSScF1AVvXW6tGgCTHoge1v4SPwXZbK2V75guu2CDwuPCyDe7v0tEH8kDymyPBaM5C/AZvV3ovQvYss/0nszTXwPtDkiqP0wRd1t673Remm4sv7k0qSrXzireMy+E032ULLBXozKW8Hb2tFkW7VdHHnasTpVJG7aM57X1LLgfYUJWNKJF2Vk3bCqEtxD85C86QoYJjCaSRzDHs8BHUuiNBOW9wZRL1x3e2Hd7xjFz0kD73JlyHiOAG1rZuObyrHePTargDoz/6b7RRi7tiFV1E4ckUDyEcjKtltyZnp5rGnBrUF1G06U8zf/RVd5XD95"
    attr_first_name: "urn:oid:2.5.4.42"
    attr_groups: "memberOf"
awx_saml_map:
  Balmer Family Farm:
    remove_admins: false
    remove_users: false
    users: true
awx_saml_team_attr:
  saml_attr: "memberOf"
  remove: true
  team_org_map:
    - team: "AWX-Farm-Engineers"
      organization: "Balmer Family Farm"


# Global LDAP Settings
awx_ldap_enabled: false
awx_ldap_uri: ""
awx_ldap_bind_dn: ""
awx_ldap_bind_password: ""
awx_ldap_require_group: ""
awx_ldap_group_type: "GroupOfNamesType"
awx_ldap_group_search: []
awx_ldap_user_search: []
awx_ldap_attribute_map: {}
awx_ldap_user_flags_by_group: {}

# Device ID can be generated via https://1password.community/discussion/comment/563411/#Comment_563411
awx_task_env:
  HOME: /var/lib/awx
  OP_DEVICE: "{{ lookup('onepassword', '1Password - Automation', field='device_id', vault='homelab') }}"