- name: Setup Docker Composes
  hosts: docker
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Combine composes
      set_fact:
        composes: "{{ composes|default({}) | combine(hostvars[inventory_hostname]['compose_' + item]|default({})) }}"
      loop: "{{ group_names }}"
  roles:
    - ../../../../roles/yum-repos
    - ../../../../roles/firewall
    - chrisbalmer.nfs
    - ../../../../roles/docker
    - chrisbalmer.docker-compose
