---
- name: Install docker packages
  package:
    name: "{{ docker_packages }}"
    state: latest

- name: Install pip packages for managing docker
  pip:
    name: "{{ docker_pip_packages }}"

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes
