---
- name: "global: Install packages for managing repos and mirrors"
  package:
    name: "{{ mirror_packages }}"
    state: latest
    update_cache: yes

- name: "global: Turn on nginx"
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure yum mirroring
  include: yum.yml

- name: Configure apt mirroring
  include: apt.yml
