---
- name: Deploy docker containers
  community.general.docker_compose:
    project_name: pihole
    definition:
      version: '2'
      networks:
        dns:
          driver: bridge
          ipam:
            driver: default
            config:
              - subnet: 172.16.238.0/24
                gateway: 172.16.238.1
      services:
        pihole:
          container_name: pihole
          image: pihole/pihole:v5.3.4
          networks:
            dns:
              ipv4_address: 172.16.238.11 
          ports:
            - "172.21.7.211:53:53/tcp"
            - "172.21.7.211:53:53/udp"
            - "172.21.7.211:67:67/udp"
            - "172.21.7.211:8080:80/tcp"
            - "172.21.7.211:8443:443/tcp"
          environment:
            TZ: 'America/Detroit'
            DNS1: 172.16.238.12#5053
            WEBPASSWORD: Password1
          volumes:
            - '/var/pihole/etc/pihole/:/etc/pihole/'
            - '/var/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
          cap_add:
            - NET_ADMIN
          dns:
            - 127.0.0.1
          depends_on:
            - cloudflared
          restart: always
        cloudflared:
          container_name: cloudflared
          image: cloudflare/cloudflared:2020.12.0
          networks:
            dns:
              ipv4_address: 172.16.238.12
          ports:
            - 5053:5053/udp
          environment:
            TZ: 'America/Detroit'
          command: proxy-dns --port 5053 --upstream https://1.0.0.3/dns-query --upstream https://1.1.1.3/dns-query --address=0.0.0.0
          restart: always