---
- name: Get information on PiHole container
  docker_container_info:
    name: "{{ pihole_name }}"
  register: pihole_container

- name: Wait for PiHole HTTP service
  wait_for:
    host: "{{ pihole_container.container.NetworkSettings.Networks[pihole_network].IPAddress }}"
    port: "{{ pihole_test_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 600

- name: Configure conditional forwarders
  template:
    src: "11-conditional_forwards.conf.j2"
    dest: "{{ pihole_path }}/etc/dnsmasq.d/11-conditional_forwards.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart PiHole
